# Generated by Django 5.2.7 on 2025-10-17 20:00

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('summary_feed', models.TextField()),
                ('raw_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('source_url', models.URLField()),
                ('proxy_url', models.URLField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feed_url', models.URLField(unique=True)),
                ('site_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCurated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('summary_short', models.TextField(max_length=500)),
                ('summary_detailed', models.TextField()),
                ('ai_tags', models.JSONField(default=list)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curated', to='news.articleraw')),
                ('cover_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_articles', to='news.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='articleraw',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.source'),
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('share', 'Share'), ('bookmark', 'Bookmark')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='news.articlecurated')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='articlecurated',
            index=models.Index(fields=['-created_at'], name='news_articl_created_ecd449_idx'),
        ),
        migrations.AddIndex(
            model_name='articlecurated',
            index=models.Index(fields=['relevance_score'], name='news_articl_relevan_e38e88_idx'),
        ),
        migrations.AddIndex(
            model_name='articleraw',
            index=models.Index(fields=['-published_at'], name='news_articl_publish_509f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='articleraw',
            index=models.Index(fields=['url'], name='news_articl_url_bb45b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user_id', '-timestamp'], name='news_userin_user_id_0d2e50_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['article', '-timestamp'], name='news_userin_article_d28d66_idx'),
        ),
    ]
