# Generated by Django 5.2.7 on 2025-10-17 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='custom_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='source',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='fetch_interval_minutes',
            field=models.IntegerField(default=10080),
        ),
        migrations.AddField(
            model_name='source',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='max_articles_per_fetch',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='source',
            name='requires_javascript',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeedIngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=10)),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_created', models.IntegerField(default=0)),
                ('articles_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='news.source')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='news_feedin_started_5b9a51_idx'), models.Index(fields=['source', '-started_at'], name='news_feedin_source__227584_idx'), models.Index(fields=['status'], name='news_feedin_status_042df6_idx')],
            },
        ),
    ]
