# Generated by Django 5.2.7 on 2025-10-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_source_custom_headers_source_error_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleraw',
            name='media_assets',
            field=models.ManyToManyField(blank=True, related_name='articles', to='news.mediaasset'),
        ),
    ]
