# Generated by Django 5.2.7 on 2025-10-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articleraw_media_assets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('audio_file', models.FileField(upload_to='audio_segments/')),
                ('script_text', models.TextField()),
                ('article_ids', models.JSONField(default=list)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='news_audios_date_6e53bb_idx')],
            },
        ),
    ]
