"""
Django settings for genienews_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Production check
IS_PRODUCTION = os.getenv('ENVIRONMENT') == 'production'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-jml3u_s!1czxm2!w-0+t-3k$aqe_h)ntr$#p-e0pppov*_e^jl')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
if IS_PRODUCTION:
    ALLOWED_HOSTS.extend(['.sevalla.com', '.sevalla.app'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'pgvector.django',
    # Local apps
    'news',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'genienews_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '..', 'frontend', 'dist')],  # React build directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'genienews_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if IS_PRODUCTION:
    # Use DATABASE_URL in production (Fly.io, Render, etc.)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.getenv('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local development database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'genienews'),
            'USER': os.getenv('DB_USER', 'genienews_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'genienews_password'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Include React build static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', 'frontend', 'dist', 'assets'),  # React build assets
]

# Use WhiteNoise for static file serving in production
if IS_PRODUCTION:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Settings
# In development, allow all origins for ease of use
# In production, specify allowed origins
if IS_PRODUCTION:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://localhost:3000',
    ]
    # Add production frontend URL from environment
    frontend_url = os.getenv('FRONTEND_URL')
    if frontend_url:
        CORS_ALLOWED_ORIGINS.append(frontend_url)
else:
    # Development: allow all origins
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'pragma',
    'expires',
]

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Celery Configuration
# Use REDIS_URL in production (from Upstash or Fly.io Redis)
if IS_PRODUCTION:
    redis_url = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
    CELERY_BROKER_URL = redis_url
    CELERY_RESULT_BACKEND = redis_url
else:
    CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
    CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Schedule for Weekly Feed Ingestion
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'ingest-feeds-weekly': {
        'task': 'news.tasks.ingest_all_feeds_task',
        'schedule': crontab(day_of_week=1, hour=2, minute=0),  # Every Monday at 2 AM
    },
    'fetch-missing-content-weekly': {
        'task': 'news.tasks.fetch_missing_content_task',
        'schedule': crontab(day_of_week=1, hour=4, minute=0),  # Every Monday at 4 AM (after ingestion)
    },
    'curate-articles-hourly': {
        'task': 'news.tasks.curate_articles_task',
        'schedule': crontab(minute=0),  # Every hour on the hour
    },
}

# Feed Ingestion Configuration
FEED_FETCH_TIMEOUT = int(os.getenv('FEED_FETCH_TIMEOUT', '30'))
FEED_USER_AGENT = os.getenv('FEED_USER_AGENT', 'GenieNewsBot/1.0')
CONTENT_FETCH_TIMEOUT = int(os.getenv('CONTENT_FETCH_TIMEOUT', '60'))
MAX_RETRIES = int(os.getenv('MAX_RETRIES', '3'))
ENABLE_PLAYWRIGHT = os.getenv('ENABLE_PLAYWRIGHT', 'false').lower() == 'true'
PLAYWRIGHT_HEADLESS = os.getenv('PLAYWRIGHT_HEADLESS', 'true').lower() == 'true'
RATE_LIMIT_DELAY = int(os.getenv('RATE_LIMIT_DELAY', '3'))

# OpenAI Configuration
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', 'sk-mock-key-replace-later')
AI_MODEL = os.getenv('AI_MODEL', 'gpt-4')
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'text-embedding-3-small')
AI_TEMPERATURE = float(os.getenv('AI_TEMPERATURE', '0.3'))
AI_MAX_TOKENS = int(os.getenv('AI_MAX_TOKENS', '1000'))

# AI Curation Configuration
AI_RELEVANCE_KEYWORDS = os.getenv(
    'AI_RELEVANCE_KEYWORDS',
    'artificial intelligence,machine learning,AI,deep learning,neural networks,'
    'LLM,GPT,transformers,computer vision,NLP,natural language processing,'
    'robotics,AI research,generative AI,large language model,autonomous systems,'
    'reinforcement learning'
).split(',')
AI_RELEVANCE_THRESHOLD = float(os.getenv('AI_RELEVANCE_THRESHOLD', '0.3'))
AI_BATCH_SIZE = int(os.getenv('AI_BATCH_SIZE', '20'))

# Text-to-Speech (TTS) Configuration for Audio Generation
TTS_VOICE = os.getenv('TTS_VOICE', 'nova')  # Options: alloy, echo, fable, onyx, nova, shimmer, maple (if available)
TTS_SPEED = float(os.getenv('TTS_SPEED', '1.15'))  # Speed: 0.25 to 4.0 (1.15 = 15% faster for ~5min content)
TTS_MODEL = os.getenv('TTS_MODEL', 'tts-1-hd')  # Options: tts-1, tts-1-hd

# Media Files Configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
